### ISSUE TITLE
BigQuery exporter: multiple SLO but one row

### ISSUE THREAD

**Issue by Eraac** [google/slo-generator#185]
I've 3 SLOs (one per continent Asia/Europe/America), who share the same config

Only these 4 values change
- metadata.name
- metadata.labels['location']
- spec.service_level_indicator.filter_good
- spec.service_level_indicator.filter_valid

```yaml
apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: entrypoint-ingestion-availability-asia
  labels:
    slo_name: availability
    service_name: entrypoint
    feature_name: ingestion
    scope: internal
    source: load-balancer
    location: asia-east2
    provider: gcp
spec:
  goal: 0.999
  description: xxx
  backend: cloud_monitoring/sre
  error_budget_policy: default
  exporters:
  - bigquery/sre

  method: good_bad_ratio
  service_level_indicator:
    filter_good: >
      project = "XXX"
      metric.type = "loadbalancing.googleapis.com/https/request_count"
      resource.type = "https_lb_rule"
      resource.label.backend_target_name = "entrypoint-default"
      metric.label.proxy_continent = "Asia"
      metric.label.response_code_class >= 200
      metric.label.response_code_class <= 400

    filter_valid: >
      project = "XXX"
      metric.type = "loadbalancing.googleapis.com/https/request_count"
      resource.type = "https_lb_rule"
      resource.label.backend_target_name = "entrypoint-default"
      metric.label.proxy_continent = "Asia"
```

When I run `slo-generator compute -c config -f slo/ --export` only one row is written into BigQuery, but if I run each file independently, all the rows is correctly write into BigQuery
