### ISSUE TITLE
Run CI with multiple versions of Python

### ISSUE THREAD

**Issue by lvaylet** [google/slo-generator#255]
The CI currently runs on the latest supported version (3.9).

With [matrix strategies](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs), GitHub supports running jobs with multiple versions of a language to make sure we cover all the versions advertised in `setup.py`.

An example here: https://github.com/google/importlab/blob/main/.github/workflows/ci.yml

```yaml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ['3.6','3.7','3.8', '3.9','3.10', '3.11-dev']
    steps:
    - uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: pip install networkx>=2 pytype

    - name: Type-Check
      if: matrix.python-version != '3.11-dev'
      run: pytype -j auto

    - name: Run Tests
      run: ./tests/run_all.sh
```
