### ISSUE TITLE
The Cloud Run deployment used in CI reports a lot of errors

### ISSUE THREAD

**Issue by lvaylet** [google/slo-generator#274]
Investigate why so many errors show up in the logs:

![image](https://user-images.githubusercontent.com/10340090/197599766-17ed02c3-e7f5-4af7-9965-c84e3a346a1b.png)

Where does this `projectId` comes from? 

Full logs available at https://pantheon.corp.google.com/run/detail/europe-west1/slo-generator/logs?project=slo-generator-ci-a2b4

**Comment by lvaylet** [comment]
A file with the same name and the same contents can be found at the root of the bucket. This file was created on Jan 25, 2022.

**Comment by lvaylet** [comment]
The local test fails with:

```
AttributeError: 'CloudMonitoringBackend' object has no attribute 'basic_sli'
```

That is not surprising. The Cloud Monitoring Backend does not have any `basic_sli` method, unlike the Cloud Service Monitoring backend which has indeed a `basic` method as well as a `basic_cli` variable:

```python
        if method == "basic":
            methods = measurement.get("method", [])
            locations = measurement.get("location", [])
            versions = measurement.get("version", [])
            threshold = measurement.get("latency", {}).get("threshold")
            slo["service_level_indicator"] = {"basic_sli": {}}
            basic_sli = slo["service_level_indicator"]["basic_sli"]
```

In addition, the Cloud Service Monitoring backend has a `slo_gae_app_availability_basic.yaml` sample very close to the on in the bucket:

```yaml
apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: gae-app-availability-basic
  labels:
    service_name: gae
    feature_name: app
    slo_name: availability-basic
spec:
  description: Availability of App Engine app
  error_budget_policy: cloud_service_monitoring
  backend: cloud_service_monitoring
  method: basic
  exporters: []
  service_level_indicator:
    app_engine:
      project_id: ${GAE_PROJECT_ID}
      module_id: ${GAE_MODULE_ID}
    availability: {}
  goal: 0.98
```

The only functional differences are:
- the `apiVersion` fields: `cloud.google.com/v1` vs `sre.google.com/v2`,
- the `error_budget_policy` fields: none vs. `cloud_service_monitoring`,
- the `method` fields: `basic_sli` vs. `basic`.

Is it possible the SLO definitions stored in the bucket are from an earlier version of SLO Generator? Would it make sense to migrate them (with the SLO Generator)?
