### ISSUE TITLE
Discrepancy on environment variable naming in Cloud Monitoring backends

### ISSUE THREAD

**Issue by lvaylet** [google/slo-generator#285]
The `project_id` variable is referred to as `STACKDRIVER_HOST_PROJECT_ID` in `samples/config.yaml`, `samples/config_export.yaml` and `samples.env.sample` while `samples/README.md` mentions a `WORKSPACE_PROJECT_ID` variable with the same purpose:

`samples/config.yaml`:

```yaml
backends:
  cloud_monitoring:
    project_id: ${STACKDRIVER_HOST_PROJECT_ID}
  cloud_monitoring_mql:
    project_id: ${STACKDRIVER_HOST_PROJECT_ID}
  cloud_service_monitoring:
    project_id: ${STACKDRIVER_HOST_PROJECT_ID}
```

`samples/README.md`:

```
### `cloud_monitoring`

| Environment variable | Description |
| --- | --- |
| `WORKSPACE_PROJECT_ID` | Cloud Monitoring host project ID |
[...]

### `cloud_monitoring_mql`

| Environment variable | Description |
| --- | --- |
| `WORKSPACE_PROJECT_ID` | Cloud Monitoring host project ID |
[...]

### `cloud_service_monitoring`

| Environment variable | Description |
| --- | --- |
| `WORKSPACE_PROJECT_ID` | Cloud Monitoring host project ID |
[...]
```
Users might get confused, even if the explanation is as simple as [Google Cloud renaming Stackdriver to Cloud Operations](https://bluemedora.com/google-operations-is-here-but-wheres-stackdriver/).
