### ISSUE TITLE
💡 [REQUEST] - Add Cloud Run example(s) to Cloud Monitoring backends

### ISSUE THREAD

**Issue by lvaylet** [google/slo-generator#303]
### Summary

We have examples for App Engine, Pub/Sub and Load Balancer. Cloud Run probably deserves its own example(s) too, as it is becoming more and more popular.

### Basic Example

`slo_cloudrun_service_availability.yaml` (with MQL):

```yaml
apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: cloudrun-service-availability
  labels:
    service_name: cloudrun
    feature_name: service
    slo_name: availability
spec:
  description: Availability of Cloud Run service
  backend: cloud_monitoring_mql
  method: good_bad_ratio
  exporters:
  - cloud_monitoring
  - bigquery
  service_level_indicator:
    filter_good: >
      fetch cloud_run_revision
      | metric 'run.googleapis.com/request_count'
      | filter resource.project_id == 'slo-generator-demo'
      | filter resource.service_name == 'cloud-run-randomly-fails'
      | filter metric.response_code_class == '2xx'
    filter_valid: >
      fetch cloud_run_revision
      | metric 'run.googleapis.com/request_count'
      | filter resource.project_id == 'slo-generator-demo'
      | filter resource.service_name == 'cloud-run-randomly-fails'
  goal: 0.75
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Drawbacks

None.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
