### ISSUE TITLE
🐛 [BUG] - use built-in metric to create Latency  SLO On  Dynatrace

### ISSUE THREAD

**Issue by GeoffroyLatourDK** [google/slo-generator#342]
### SLO Generator Version

v2.3.4

### Python Version

3.10.11

### What happened?

in the documentation, we're shown using the threshold method with an ext: metric from a OneAgent or ActiveGate extension.

```ext:app.request_latency```
is this mandatory, or can we use built-in metrics like those ones ? 

``` builtin:service.response.client```
``` builtin:service.keyRequest.response.time ```

 it can be great to add a kind of list of metric that we can use in the documentation :) 

### What did you expect?

expected to have a valid result using those two builtin metrics 
``` builtin:service.response.client```
``` builtin:service.keyRequest.response.time ```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lvaylet** [comment]
Hi @GeoffroyLatourDK, thanks for reporting this behavior. Have you actually tried using these built-in metrics? If so, could you share the output and error message(s). Ideally I'd like to reproduce the issue.

**Comment by GeoffroyLatourDK** [comment]
Hello @lvaylet, 
As you can see on the screenshot below, I don't have any output errors, but a miscalculation in the number of good and bad events.
![image](https://github.com/google/slo-generator/assets/116006175/9d70ac7e-0ddc-4d9c-b935-35d473be27e1)


In fact, it's more the number of events that doesn't seem to correspond. On the screenshot below,
![image](https://github.com/google/slo-generator/assets/116006175/47ad2b13-ef0b-4c56-8c6f-1046fdc340fb)

 I'm using the builtin:service.errors.client.successCount metric, which allows me to calculate the number of successful calls. There's a big difference between the 6k83 calls on one side and the 60 calls on the other.

**Comment by lvaylet** [comment]
Can you share your SLO definition, either as YAML or JSON?

**Comment by GeoffroyLatourDK** [comment]
Hello @lvaylet of course !
 I just had to annonymize the names but the structure and metrics used remain identical.

```
apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name:  dummy name
  labels:
    service_name:  dummy name
    feature_name:  dummy name
    slo_name:  dummy name
spec:
  description: dummy name
  backend: dynatrace/prod
  method: threshold
  service_level_indicator:
    query_valid:
      metric_selector: builtin:service.response.time
      entity_selector: type("service"),entityName("Dummy service")
    threshold: 200000.000         # us
  goal: 0.95
  frequency: '*/5 * * * *'

```
