### ISSUE TITLE
🐛 [BUG] - Similar GitHub Actions workflows have different triggers

### ISSUE THREAD

**Issue by lvaylet** [google/slo-generator#385]
### SLO Generator Version

v2.5.2

### Python Version

3.7

### What happened?

`.github/workflows/build-and-push-to-gcr.yml` and `.github/workflows/build-and-push-to-ghcr.yml` have related purposes but different triggers:

```yaml
on:
  push:
    branches: ['main']
    tags: ['v*.*.*']
```

vs.

```yaml
on:
  push:
    branches:
      - master
      - deploy-*
    tags:
      - v*.*.*
```

### What did you expect?

Related workflows should have the same triggers.

Use the same triggers for both workflows.

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
